language: php
php:
- 7.0
- 7.1
#   - hhvm
install:
- travis_retry composer self-update
- travis_retry composer require satooshi/php-coveralls "^1" --no-update --dev
- travis_retry composer install
before_script:
- phpenv rehash
script:
  - phpunit -c phpunit.xml.dist
after_success:
- php vendor/bin/coveralls -v
cache:
  apt: true
  directories:
  - vendor
